version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - OPENAI_API_KEY=$OPENAI_API_KEY
    volumes:
      - .:/app
    command: ["sh", "-c", "gpte ./projects/example"]

